server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 32m;
    charset utf-8;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
        try_files $uri =404;
    }

    location /dev-vrm-assets/ {
        expires 1d;
        add_header Cache-Control "public, max-age=86400";
        try_files $uri =404;
    }

    location / {
        default_type text/html;
        try_files $uri $uri/ /index.html;
    }
}
